### ISSUE TITLE
typos and extraction issue

### ISSUE THREAD

**Issue by tromp** [AdamISZ/from0k2bp#10]
on page 23, there are four lines using x . dy . y . dx instead of x . dy + y . dx
also, how do you compute z there without having x . dy + y . dx available (it seems you only know its commitment).

**Comment by AdamISZ** [comment]
I see nothing like that on p. 23 of the latest pdf in this repo, I'm guessing you must be using an old version? (also please see #2 and so download rather than read it inline, or use the .tex). I think it must be stuff earlier than p.23 on the current pdf, but let me know.

**Comment by tromp** [comment]
Indeed; i had printed out an earlier version. It's fixed on page 21 of Section 4.5 in the current version.
I'm still puzzled on how to compute z in the last line, as x · d_y + y · d_x appears to be available only in committed form C_1.

**Comment by AdamISZ** [comment]
I think there may be some additional details to consider, but from reading through it again, it seems clear to me that you should consider that whole section in its entirety; given the two accepting transcripts, you can extract x, y, dx, dy as per the previous two pages, and then go on to use those values in that last section for z.

**Comment by tromp** [comment]
You're right;  x, y, dx, dy could have been previously extracted. So it all checks out...
