### ISSUE TITLE
about ZK stuffs

### ISSUE THREAD

**Issue by baro77** [AdamISZ/from0k2bp#16]
Not really an issue, but regarding sentence on page 9/10:

> In academic coverage of this concept, there are a lot additional definitions used. A “witness” is a piece of (usually secret) data corresponding to a “state- ment” which the Prover possesses but does not want to reveal. Zero knowledge comes in flavours such as “Honest Verifier Zero Knowledge” with a number of subcategories

I just want to signal I have recently closed an A3/tabloid size cheat-sheet about that stuff at a level I think suitable to _from0k2bp_ typical readers:
https://github.com/baro77/ZKbasicsCS
It also quickly deals with Fiat-Shamir NIZK heuristic recalled in section 6.2.4

Thanks for your inspiring document!

BTW I don't open a PR cause it's more an automation-issue I guess, but I take the occasion to notice that pre-compiled PDF in your repo is missing the recent PRs by robot-dreams

**Comment by AdamISZ** [comment]
> BTW I don't open a PR cause it's more an automation-issue I guess, but I take the occasion to notice that pre-compiled PDF in your repo is missing the recent PRs by robot-dreams

Thanks, I hadn't forgotten but left it for a while because I had to do some latex package setup on this machine. Should be done now.

> https://github.com/baro77/ZKbasicsCS

Nice, you have some good references on that poster :) I've read or at least have most of those resources myself :)

> Thanks for your inspiring document!

You're welcome.

**Comment by baro77** [comment]
thanks! So I close the issue! 
Best regards!
