### ISSUE TITLE
Equations showing calculation of (z,s) missing

### ISSUE THREAD

**Issue by avras** [AdamISZ/from0k2bp#3]
https://github.com/AdamISZ/from0k2bp/blob/bc5c53dffbad2e96f7f25036b1b79012f4cef486/testzkp.tex#L532

There is some math missing on page 8 between the sentences 
"These last two are calculated as:"  AND "Note that the summations.."

**Comment by AdamISZ** [comment]
Thanks for leaving the note. I see. Unfortunately I have been busy with other projects and haven't had time to update; there still seems to be an issue with how the pdf gets built here.

Please use the version at https://joinmarket.me/static/FromZK2BPs_v1.pdf if you just want to read.

**Comment by AdamISZ** [comment]
Fixed in 0f719da8b3674d77137fc2393f5d84d580f8d1c9

There will doubtless be a few more lurking in there ...

**Comment by avras** [comment]
Thanks. I will give the latest version a try. Keep up the good work with these explainers.
