### ISSUE TITLE
Number of commitments / revelations in Section 5.1 example

### ISSUE THREAD

**Issue by laiyingtong** [AdamISZ/from0k2bp#7]
Hi Adam, at the end of Section 5.1 (Condensing a single vector), we consider the example starting with a 600-dimension vector, which we first chunk into ten 60-dimensional vectors, and then again into ten 6-dimensional vectors. Shouldn't the number of commitments / revelations in this example be 10 × 2-1 diagonals + 10 × 2-1 diagonals + 6 scalars = 19 + 19 + 6 = 44 items, instead of 43 as stated?

**Comment by laiyingtong** [comment]
Realised that we have to subtract 1 for the starting _A_ . But it would be helpful if the line stating "That requires revealing 2 × 10 − 1 = 18 commitments..." could be changed to "2 × 10 − 1 = 19 commitments". Closing the issue now.

**Comment by AdamISZ** [comment]
Thanks for correction, fixed in 7b3c6dbe121c5fd8eaad5d018c39c4b2aff0bbe7
